language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script: 
  - pytest -v --cov-report term-missing --cov=app

branches:
  except:
  - master
  only:
  - ch-API-160779636

after_success:
  - coveralls

notifications:
  email: false
